In [1]:
import numpy as np

In [2]:
np.arange(0, 5, 0.5, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
np.arange(-3, 3, 0.5, dtype=int)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [4]:
np.arange(3)

array([0, 1, 2])

In [5]:
np.arange(3.0)

array([0., 1., 2.])

In [6]:
np.arange(3,7)

array([3, 4, 5, 6])

In [7]:
np.arange(3,7,2)

array([3, 5])